### ISSUE TITLE
请问关于调用methods方法，并传值最终是通过什么方法解决的呢？

### ISSUE THREAD

**Issue by tode-chen** [noahlam/articles#1]
您的文章对新手学习MPVUE很有帮助，很快的了解了一些坑如何避免。
不过有些地方没看懂，能帮忙在说一下吗？
请问关于调用methods方法，并传值最终是通过什么方法解决的呢？

二, 这个也是比较难受的地方,就是模板的数据绑定里面,没办法在模板语法里面调用methods方法 (或者说没办法调用computed以外的函数),有人也许会说,那可以用computed属性,那如果我想给函数传参怎么办? 看下面代码:

**Comment by noahlam** [comment]
你在模板里面调用method的时候,无非就是调用一个方法,来处理某些数据,并最终得到一个值,渲染出来.那么我们是不是可以提前计算出这个值,然后就直接{{xxxx}}渲染出来呢?
