### ISSUE TITLE
咨询一个问题，开发完以后，npm run build 然后上传 体验版  首页白屏

### ISSUE THREAD

**Issue by huanhuanhome** [noahlam/articles#3]
咨询一个问题，开发完以后，npm run build 然后上传 体验版 
出现的问题：
首页白屏

尝试解决：
开启调试模式可以选择去首页，然后这样的方式跳转到首页是正常的

代码：

没有数据请求，全是静态页面，没有报错

**Comment by noahlam** [comment]
接口的地址不在小程序配置的信任名单里面。去小程序后台加入一下就可以了。
