### ISSUE TITLE
JS中的继承两点建议

### ISSUE THREAD

**Issue by ShuBuShao** [noahlam/articles#4]
大佬的文章写的很棒. 读后很有收获.

有两点笔误指出一下:
1. JS中的继承(下)中, 寄生组合式继承示例中, 使用`inherit`的地方, 应该是`inherit(Student, Person)`?
2. JS中的继承(上)中, 演示原型链继承的示例代码中, 没有修改子类构造函数的指向, 否则子类实例的构造函数会指向父类

**Comment by noahlam** [comment]
已更正，感谢大佬指出。

**Comment by ShuBuShao** [comment]
感谢大佬
